---
plugins:
  - "jest"
  - "@typescript-eslint"

env:
  node: true
  es2020: true

parser: "@typescript-eslint/parser"

extends:
  - "airbnb-typescript/base"
  - "plugin:jest/recommended"

parserOptions:
  ecmaVersion: 11
  sourceType: module
  project: ./tsconfig.eslint.json
